application: ninn-boom
version: 1
runtime: go
api_version: go1

skip_files:
- ^node_modules/.*
- ^.tmp/.*
- ^e2e/.*
- ^client/.*
- ^(.*/)?package\.json
- ^(.*/)?gulpfile\.js
- ^(.*/)?app\.yaml
- ^(.*/)?bower\.json
- ^(.*/)?karma\.conf\.js
- ^(.*/)?protractor\.conf\.js

handlers:
- url: /app
  static_dir: dist/public/app
- url: /assets
  static_dir: dist/public/assets
- url: /bower_components
  static_dir: dist/public/bower_components

- url: /.*
  script: _go_app
  secure: always
